### ISSUE TITLE
Service is missing healthcheck

### ISSUE THREAD

**Issue by janderson2** [companieshouse/document-generator-accounts#24]
The following enhancements should be implemented to ensure that this service is consistent with our expected standards:

* A minimal HTTP server should be added, along with support for a command line flag that specifies the interface and port number on which to listen for incoming requests
* A `/healthcheck` route should be added for monitoring service health
* The `start.sh` script should ensure that the port number is passed to the app during startup
* A default `PORT` value should set in the `start.sh` script if no port number if accessible via the environment

**Comment by rafahop** [comment]
Closing as this has now been implemented and merged into develop by @jterrych in #39
